export const output = {
  initialised: true,
  kits: [
    {
      path: 'KITS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'KIT000',
      newName: '000 TR-808',
      prettyName: '000 Kit',
      presetType: 'KIT',
      presetName: 'KIT000',
    },
    {
      path: 'KITS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'KIT001',
      newName: '001 DDD-1',
      prettyName: '001 Kit',
      presetType: 'KIT',
      presetName: 'KIT001',
    },
    {
      path: 'KITS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'Shakers',
      newName: '',
      prettyName: '',
      presetType: 'KIT',
      presetName: 'Shakers',
    },
    {
      path: 'KITS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'Space Sample',
      newName: '',
      prettyName: '',
      presetType: 'KIT',
      presetName: 'Space Sample',
    },
  ],
  synths: [
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT005',
      newName: '005 Sweet Mono Bass',
      prettyName: '005 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT005',
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT006',
      newName: '006 Vaporwave Bass',
      prettyName: '006 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT006',
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT007',
      newName: '007 Detuned Saw Bass',
      prettyName: '007 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT007',
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT008',
      newName: '008 FM Rich Distorted Bass',
      prettyName: '008 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT008',
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT170',
      newName: '170 Sitar',
      prettyName: '170 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT170',
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: "SYNT172 'copy'",
      newName: '',
      prettyName: "172 Synth 'copy'",
      presetType: 'SYNT',
      presetName: "SYNT172 'copy'",
    },
    {
      path: 'SYNTHS',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT172',
      newName: '',
      prettyName: '172 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT172',
    },
    {
      path: 'SYNTHS/subdir',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'Mellotron Stringsection',
      newName: '',
      prettyName: '',
      presetType: 'SYNT',
      presetName: 'Mellotron Stringsection',
    },
    {
      path: 'SYNTHS/subdir',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'New1',
      newName: '',
      prettyName: '',
      presetType: 'SYNT',
      presetName: 'New1',
    },
    {
      path: 'SYNTHS/subdir',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'Pszch',
      newName: '',
      prettyName: '',
      presetType: 'SYNT',
      presetName: 'Pszch',
    },
    {
      path: 'SYNTHS/subdir',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'SYNT000',
      newName: '000 Rich Saw Bass',
      prettyName: '000 Synth',
      presetType: 'SYNT',
      presetName: 'SYNT000',
    },
    {
      path: 'SYNTHS/subdir',
      rootPath: '/Users/alexreid/work/Deluge_SD_Updater/packages/main/tests/dummySDCard',
      rewriteName: '',
      oldName: 'String Pad',
      newName: '',
      prettyName: '',
      presetType: 'SYNT',
      presetName: 'String Pad',
    },
  ],
  songs: [
    {
      name: '1Aa New Zears',
      path: 'SONGS',
      instruments: [
        {
          type: 'sound',
          presetName: 'Latelz',
          presetFolder: null,
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'nameonly',
          patchName: '',
          usedInClips: [3],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: null,
          presetFolder: null,
          presetSlot: 35,
          presetSubSlot: -1,
          formatType: 'old',
          patchName: 'KIT035',
          usedInClips: [0],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: null,
          presetFolder: null,
          presetSlot: 41,
          presetSubSlot: -1,
          formatType: 'old',
          patchName: 'KIT041',
          usedInClips: [1, 9],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: null,
          presetFolder: null,
          presetSlot: 44,
          presetSubSlot: -1,
          formatType: 'old',
          patchName: 'KIT044',
          usedInClips: [2],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: null,
          presetFolder: null,
          presetSlot: 43,
          presetSubSlot: -1,
          formatType: 'old',
          patchName: 'KIT043',
          usedInClips: [5],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: 'Space Sample',
          presetFolder: null,
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'nameonly',
          patchName: '',
          usedInClips: [6, 7, 8],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: 'Shakers',
          presetFolder: null,
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'nameonly',
          patchName: '',
          usedInClips: [4, 10],
          rewriteName: '',
          rewriteFolder: '',
        },
      ],
      clipsLength: 11,
      firmwareVersion: ['3', '1', '5'],
    },
    {
      name: 'Break Deep',
      path: 'SONGS',
      instruments: [
        {
          type: 'kit',
          presetName: '003',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'KIT003',
          usedInClips: [0],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: '000',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'KIT000',
          usedInClips: [1],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: '163',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'SYNT163',
          usedInClips: [2],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: '171',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'SYNT171',
          usedInClips: [3],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'String Pad',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [4],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: '044',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'KIT044',
          usedInClips: [5],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: '043',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'numsonly',
          patchName: 'KIT043',
          usedInClips: [6],
          rewriteName: '',
          rewriteFolder: '',
        },
      ],
      clipsLength: 7,
      firmwareVersion: ['4', '1', '3'],
    },
    {
      name: 'Filesystem',
      path: 'SONGS',
      instruments: [
        {
          type: 'kit',
          presetName: 'KIT043',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [2],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'SYNT171',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [3],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: 'KIT000 2',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'newsuffix',
          patchName: '',
          usedInClips: [4],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: 'KIT000',
          presetFolder: 'KITS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [5],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'SYNT009 2',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'newsuffix',
          patchName: '',
          usedInClips: [6],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'bass Dist Fat 2',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [8],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'SYNT009',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [7],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'bass Dist Fat',
          presetFolder: 'SYNTHS',
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'new',
          patchName: '',
          usedInClips: [9],
          rewriteName: '',
          rewriteFolder: '',
        },
      ],
      clipsLength: 10,
      firmwareVersion: ['4', '1', '2'],
    },
    {
      name: 'Unfinished',
      path: 'SONGS',
      instruments: [
        {
          type: 'sound',
          presetName: null,
          presetFolder: null,
          presetSlot: 34,
          presetSubSlot: 0,
          formatType: 'old',
          patchName: 'SYNT034A',
          usedInClips: [0],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'kit',
          presetName: null,
          presetFolder: null,
          presetSlot: 5,
          presetSubSlot: -1,
          formatType: 'old',
          patchName: 'KIT005',
          usedInClips: [1],
          rewriteName: '',
          rewriteFolder: '',
        },
        {
          type: 'sound',
          presetName: 'String Pad',
          presetFolder: null,
          presetSlot: null,
          presetSubSlot: null,
          formatType: 'nameonly',
          patchName: '',
          usedInClips: [2, 3],
          rewriteName: '',
          rewriteFolder: '',
        },
      ],
      clipsLength: 4,
      firmwareVersion: ['3', '1', '5'],
    },
  ],
};
